services:
  - name: po-form
    buildCommand: npm install
    startCommand: node server.js
    regions:
      - oregon
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000